name: buddha_mindfulness
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:
  flutter_svg:
  connectivity_plus:
  get_it:
  get_storage:
  cloud_firestore: ^4.3.1
  get: 4.6.5
  cached_network_image:
  insta_image_viewer: ^1.0.2
  video_player:
  chewie: ^1.3.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
dependency_overrides:
  firebase_core_platform_interface: 4.5.2

flutter: 
  uses-material-design: true

